theme = "ayu_evolve"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
popup-border = "all"
true-color = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "all"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "spacer", "version-control"]
right = ["diagnostics", "selections", "register", "position", "file-line-ending", "file-type"]
