theme = "snazzy"

[editor]
line-number = "relative"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.whitespace]
render = "all"

[keys.insert]
k = { j = "normal_mode" }
